### PR TITLE
bug fixed in README.md

### PR DESCRIPTION
**Pull request by jakezhaojb**
right way to visit generator in python

### CODE REVIEW

**Comment by rabitt** [comment]
The object returned by ```load_all_multitracks``` is a list, so it's not a generator.
```
In  [2]: mtrack_list = mdb.load_all_multitracks()
In  [3]: multitrack_1 = next(mtrack_list)
TypeError                                 Traceback (most recent call last)
<ipython-input-5-b66648a3723e> in <module>()
----> 1 mtrack1 = next(mtrack_list)

TypeError: list object is not an iterator
```

**Comment by jakezhaojb** [comment]
So what happens to my installation at the following:

    In [3]: mtrack_list = mdb.load_all_multitracks()

    In [4]: mtrack_list[0]
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-4-5dfc15ad6b15> in <module>()
    ----> 1 mtrack_list[0]

     TypeError: 'generator' object has no attribute '__getitem__'

    In [5]: next(mtrack_list)
    Out[5]: <medleydb.multitrack.MultiTrack at 0x10bc40dd0>

**Comment by jakezhaojb** [comment]
Also I believe the generator is a better way than list because it involves no storage burden?

**Comment by rabitt** [comment]
Ah sorry, you're right. The object returned by ```load_all_multitracks``` was updated and I hadn't pulled since.

**Pull request merged**
